apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-react-kubernetes
  labels:
    app: deploy-react-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-react-kubernetes
  template:
    metadata:
      labels:
        app: deploy-react-kubernetes
    spec:
      containers:
      - name: deploy-react-kubernetes
        image: bhuang019/deploy-react-kubernetes
        ports:
        - containerPort: 80